-- ---------- CLEANUP (child -> parent) ----------
TRUNCATE TABLE MEMBER_PRODUCT_EFFECT;
TRUNCATE TABLE MEMBER_PRODUCT;
TRUNCATE TABLE PRODUCT_EFFECT;
TRUNCATE TABLE PRODUCT;
TRUNCATE TABLE EFFECT;
TRUNCATE TABLE CATEGORY;

-- ---------- SEED ----------
INSERT INTO CATEGORY (CATEGORY_ID, CATEGORY_NAME)
VALUES (100, '스킨케어');

INSERT INTO EFFECT (EFFECT_ID, EFFECT_NAME)
VALUES (1, '보습');
INSERT INTO EFFECT (EFFECT_ID, EFFECT_NAME)
VALUES (2, '진정');

-- 정상 상품(삭제 아님)
INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, BRAND_NAME, RECOMMENDED_PERIOD, BH_TYPE, CATEGORY_ID)
VALUES (10, '앰플A', '브랜드A', 90, 1, 100);

-- 삭제된 상품(검증용)
INSERT INTO PRODUCT (PRODUCT_ID, PRODUCT_NAME, BRAND_NAME, RECOMMENDED_PERIOD, BH_TYPE, CATEGORY_ID,
                     DELETED_AT)
VALUES (20, '앰플B', '브랜드B', 60, 1, 100, SYSTIMESTAMP);

-- 상품 효과 (앰플A → 보습/진정)
INSERT INTO PRODUCT_EFFECT (PRODUCT_ID, EFFECT_ID)
VALUES (10, 1);
INSERT INTO PRODUCT_EFFECT (PRODUCT_ID, EFFECT_ID)
VALUES (10, 2);
